# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20e61a51fdc99e04b72334076428a576f586c2bedcf0a711537b3bb5fb89b6ff99417f00c12d8873c7875aa56946946e6cb12d796c97e46dbf2d75cb6be146e5

test:
  secret_key_base: 587f9c04ee8de551c381f475b6346106bdd0465be08d1424ddbd292dd2c1e6359fbac7e14dbb08bc8ee777247822b52bb2a8045879f8fe22124b5643a4cd7860

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
